- 
  name: Play 2
  hosts: webserver1
  tasks:
    - name: creates users files
      file:
        path: /tmp/ansible-{{ item }}
        state: touch
      loop:
        - Krunal
        - Het
        - Yogi